version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=alphaentropy
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/alphaentropy --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alphaentropy-microservice
    ports:
      - "8080:8080"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=alphaentropy
      - SPRING_PROFILES_ACTIVE=prod
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: wget -q --spider http://localhost:8080/api/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
